### ISSUE TITLE
Levantamento de requisitos

### ISSUE THREAD

**Issue by izabellaalves** [fga-eps-mds/HEART-hub-fga-inovacao#3]
# Levantamento de requisitos

## Descrição
Para desenvolver o HUB Inovação FGA, faremos inicialmente algo parecido com uma "pesquisa de mercado", na qual olharemos produtos parecidos com o que visamos fazer, para levantar os requisitos principais usados por eles e decidir o que faremos no nosso.

## Tarefas

- [x] Levantar as opções disponíveis no menu do HUB de Inovação da USP

- [x] Levantar as opções disponíveis no menu do HUB da UFRJ

- [x] Detalhar o conteúdo de cada uma das opções levantadas

**Comment by Lucas13032003** [comment]
### **Levantamento de funções disponíveis dentro do HUB da USP**

**Logo na tela inicial do site percebemos que ele é estruturado em secções, para melhor descrever dividimos o site e cinco secções são elas:**

**- Secção 1:** Dentro desta temos um resumo curto e geral do site, além de uma barra de de pesquisa e alguns menus no cabeçario. 

**- Secção 2:** Dentro desta temos um resumo de todas as informações que podem ser encontradas no site.

**- Secção 3:** Dentro desta temos a explicação dos menus existentes no cabeçalho do site. **( Vale ressaltar que durante o levantamento percebemos uma redundância em relação aos botões de direcionamento de modo que podemos corrigir)**

**- Secção 4:** Dentro desta temos uma pequena apresentação de empresas parceiras, além de conter uma barra de rolagem com logo de várias empresas.

**- Secção 5:** Dentro desta temos o rodapé do site.

### **Menus/Pré-requisitos obrigatórios para todos Hub**

**1. Iniciativas:**  mostra diversas iniciativas e programas dentro da UNB possuí para facilitar e estimular a inovação e o empreendedorismo, fazendo a ponte entre o ambiente acadêmico, as organizações e a sociedade.

**2. P&D&I:** Na seção de Pesquisa & Desenvolvimento & Inovação, você encontra laboratórios, organizações e programas que atuam com desenvolvimento e inovação no âmbito da UNB.

**3. Competência:** Nesta seção, você poderá consultar quais as competências dos pesquisadores da Unb, quem são e como contatá-los.

**4. Empreendedorismo e Inovação:** Página destina a mostrar o que a UNB oferece aos seus estudantes, em a diversas disciplinas em nível de graduação e pós-graduação que se relacionam aos temas de Empreendedorismo e Inovação.

**5. Empresas:** As Empresas presente na UNB através de parceria, (Empresas Junior).

**6. Editais:** Para  informar alunos e a sociedade de editais abertos na UNB.

**7. Contato:** Local destinado para deixarmos nossos contatos e informações nossas.

**Comment by Lucas13032003** [comment]
| Pré-requisitos obrigatórios para Hub |       |                   |         |                    |        |
|--------------------------------------|-------|-------------------|---------|--------------------|--------|
| Páginas:                             | Links | Barra de pesquisa | Imagens | Carrocel de imagem | Botões |
| Iniciativas                          | X     |                   |         |                    | X      |
| P&D&I                                |       |                   |         |                    |        |
| Competência                          |       | X                 |         | X                  |        |
| Empreendedorismo e Inovação          |       |                   | X       |                    | X      |
| Empresas                             |       |                   |  X |                    | X      |
| Editais                              | X     | X                 |         |                    |        |
| Contato                              | X     |                   |         |                    |        |
| Página Inicial                       | X     | X                 |         | X                  | X      |

**Comment by algorithmorphic** [comment]
Requisitos funcionais e não funcionais do HUB FGA Inovação

Requisitos funcionais:

Cadastro de usuários: permitir que os usuários criem uma conta para acessar as funcionalidades do hub;
 
Busca de eventos: permitir que os usuários pesquisem eventos e programas de aceleração disponíveis na plataforma;

Participação em fóruns: permitir que os usuários participem de discussões e fóruns de networking;

Integração com redes sociais: permitir que os usuários compartilhem informações sobre eventos e programas de aceleração em suas redes sociais;

Cadastro de usuários: permitir que os usuários criem uma conta para acessar as funcionalidades do hub;

Busca de eventos: permitir que os usuários pesquisem eventos e programas de aceleração disponíveis na plataforma;

Participação em fóruns: permitir que os usuários participem de discussões e fóruns de networking; e

Integração com redes sociais: permitir que os usuários compartilhem informações sobre eventos e programas de aceleração em suas redes sociais.
 
Requisitos não funcionais:

Escalabilidade: o sistema deve suportar um grande número de usuários e funcionalidades sem prejudicar sua performance;

Segurança: o sistema deve garantir a segurança dos dados dos usuários e prevenir ataques e invasões;

Usabilidade: o sistema deve ser fácil de usar e navegar, com uma interface intuitiva e clara;

Disponibilidade: o sistema deve estar disponível para os usuários sempre que necessário, com um tempo mínimo de indisponibilidade para manutenção;

Performance: o sistema deve responder rapidamente às solicitações dos usuários e ter tempos de carregamento rápidos;

Confiabilidade: o sistema deve ser confiável e funcionar corretamente em todos os momentos, com tempo mínimo de 
indisponibilidade;

Acessibilidade: o sistema deve ser acessível para usuários com diferentes necessidades e deficiências, como usuários com deficiência visual ou auditiva;

Internacionalização: o sistema deve ser capaz de lidar com diferentes idiomas, moedas e formatos de data; e

Portabilidade: o sistema deve ser portátil e capaz de funcionar em diferentes plataformas e dispositivos.
